// Code generated by MockGen. DO NOT EDIT.
// Source: kmmmodule.go
//
// Generated by this command:
//
//	mockgen -source=kmmmodule.go -package=kmmmodule -destination=mock_kmmmodule.go KMMModuleAPI
//
// Package kmmmodule is a generated GoMock package.
package kmmmodule

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/ROCm/network-operator/api/v1alpha1"
	v1beta1 "github.com/rh-ecosystem-edge/kernel-module-management/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockKMMModuleAPI is a mock of KMMModuleAPI interface.
type MockKMMModuleAPI struct {
	ctrl     *gomock.Controller
	recorder *MockKMMModuleAPIMockRecorder
}

// MockKMMModuleAPIMockRecorder is the mock recorder for MockKMMModuleAPI.
type MockKMMModuleAPIMockRecorder struct {
	mock *MockKMMModuleAPI
}

// NewMockKMMModuleAPI creates a new mock instance.
func NewMockKMMModuleAPI(ctrl *gomock.Controller) *MockKMMModuleAPI {
	mock := &MockKMMModuleAPI{ctrl: ctrl}
	mock.recorder = &MockKMMModuleAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKMMModuleAPI) EXPECT() *MockKMMModuleAPIMockRecorder {
	return m.recorder
}

// SetBuildConfigMapAsDesired mocks base method.
func (m *MockKMMModuleAPI) SetBuildConfigMapAsDesired(buildCM *v1.ConfigMap, nwConfig *v1alpha1.NetworkConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBuildConfigMapAsDesired", buildCM, nwConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBuildConfigMapAsDesired indicates an expected call of SetBuildConfigMapAsDesired.
func (mr *MockKMMModuleAPIMockRecorder) SetBuildConfigMapAsDesired(buildCM, nwConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBuildConfigMapAsDesired", reflect.TypeOf((*MockKMMModuleAPI)(nil).SetBuildConfigMapAsDesired), buildCM, nwConfig)
}

// SetKMMModuleAsDesired mocks base method.
func (m *MockKMMModuleAPI) SetKMMModuleAsDesired(ctx context.Context, mod *v1beta1.Module, nwConfig *v1alpha1.NetworkConfig, nodes *v1.NodeList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKMMModuleAsDesired", ctx, mod, nwConfig, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKMMModuleAsDesired indicates an expected call of SetKMMModuleAsDesired.
func (mr *MockKMMModuleAPIMockRecorder) SetKMMModuleAsDesired(ctx, mod, nwConfig, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKMMModuleAsDesired", reflect.TypeOf((*MockKMMModuleAPI)(nil).SetKMMModuleAsDesired), ctx, mod, nwConfig, nodes)
}

// SetNodeVersionLabelAsDesired mocks base method.
func (m *MockKMMModuleAPI) SetNodeVersionLabelAsDesired(ctx context.Context, nwConfig *v1alpha1.NetworkConfig, nodes *v1.NodeList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNodeVersionLabelAsDesired", ctx, nwConfig, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNodeVersionLabelAsDesired indicates an expected call of SetNodeVersionLabelAsDesired.
func (mr *MockKMMModuleAPIMockRecorder) SetNodeVersionLabelAsDesired(ctx, nwConfig, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNodeVersionLabelAsDesired", reflect.TypeOf((*MockKMMModuleAPI)(nil).SetNodeVersionLabelAsDesired), ctx, nwConfig, nodes)
}
