// Code generated by MockGen. DO NOT EDIT.
// Source: network_config_reconciler.go
//
// Generated by this command:
//
//	mockgen -source=network_config_reconciler.go -package=controllers -destination=mock_network_config_reconciler.go networkConfigReconcilerHelperAPI
//
// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/ROCm/network-operator/api/v1alpha1"
	v1beta1 "github.com/rh-ecosystem-edge/kernel-module-management/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	controllerruntime "sigs.k8s.io/controller-runtime"
	client "sigs.k8s.io/controller-runtime/pkg/client"
	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// MocknetworkConfigReconcilerHelperAPI is a mock of networkConfigReconcilerHelperAPI interface.
type MocknetworkConfigReconcilerHelperAPI struct {
	ctrl     *gomock.Controller
	recorder *MocknetworkConfigReconcilerHelperAPIMockRecorder
}

// MocknetworkConfigReconcilerHelperAPIMockRecorder is the mock recorder for MocknetworkConfigReconcilerHelperAPI.
type MocknetworkConfigReconcilerHelperAPIMockRecorder struct {
	mock *MocknetworkConfigReconcilerHelperAPI
}

// NewMocknetworkConfigReconcilerHelperAPI creates a new mock instance.
func NewMocknetworkConfigReconcilerHelperAPI(ctrl *gomock.Controller) *MocknetworkConfigReconcilerHelperAPI {
	mock := &MocknetworkConfigReconcilerHelperAPI{ctrl: ctrl}
	mock.recorder = &MocknetworkConfigReconcilerHelperAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknetworkConfigReconcilerHelperAPI) EXPECT() *MocknetworkConfigReconcilerHelperAPIMockRecorder {
	return m.recorder
}

// buildNetworkConfigStatus mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) buildNetworkConfigStatus(ctx context.Context, nwConfig *v1alpha1.NetworkConfig, nodes *v1.NodeList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "buildNetworkConfigStatus", ctx, nwConfig, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// buildNetworkConfigStatus indicates an expected call of buildNetworkConfigStatus.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) buildNetworkConfigStatus(ctx, nwConfig, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "buildNetworkConfigStatus", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).buildNetworkConfigStatus), ctx, nwConfig, nodes)
}

// buildNodeAssignments mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) buildNodeAssignments(networkConfigList *v1alpha1.NetworkConfigList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "buildNodeAssignments", networkConfigList)
	ret0, _ := ret[0].(error)
	return ret0
}

// buildNodeAssignments indicates an expected call of buildNodeAssignments.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) buildNodeAssignments(networkConfigList any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "buildNodeAssignments", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).buildNodeAssignments), networkConfigList)
}

// deleteCondition mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) deleteCondition(ctx context.Context, condition string, nwConfig *v1alpha1.NetworkConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "deleteCondition", ctx, condition, nwConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// deleteCondition indicates an expected call of deleteCondition.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) deleteCondition(ctx, condition, nwConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "deleteCondition", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).deleteCondition), ctx, condition, nwConfig)
}

// finalizeNetworkConfig mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) finalizeNetworkConfig(ctx context.Context, nwConfig *v1alpha1.NetworkConfig, nodes *v1.NodeList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "finalizeNetworkConfig", ctx, nwConfig, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// finalizeNetworkConfig indicates an expected call of finalizeNetworkConfig.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) finalizeNetworkConfig(ctx, nwConfig, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "finalizeNetworkConfig", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).finalizeNetworkConfig), ctx, nwConfig, nodes)
}

// findNetworkConfigsForNMC mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) findNetworkConfigsForNMC(ctx context.Context, nmc client.Object) []reconcile.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "findNetworkConfigsForNMC", ctx, nmc)
	ret0, _ := ret[0].([]reconcile.Request)
	return ret0
}

// findNetworkConfigsForNMC indicates an expected call of findNetworkConfigsForNMC.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) findNetworkConfigsForNMC(ctx, nmc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "findNetworkConfigsForNMC", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).findNetworkConfigsForNMC), ctx, nmc)
}

// findNetworkConfigsForSecret mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) findNetworkConfigsForSecret(ctx context.Context, secret client.Object) []reconcile.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "findNetworkConfigsForSecret", ctx, secret)
	ret0, _ := ret[0].([]reconcile.Request)
	return ret0
}

// findNetworkConfigsForSecret indicates an expected call of findNetworkConfigsForSecret.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) findNetworkConfigsForSecret(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "findNetworkConfigsForSecret", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).findNetworkConfigsForSecret), ctx, secret)
}

// findNetworkConfigsWithKMM mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) findNetworkConfigsWithKMM(ctx context.Context, node client.Object) []reconcile.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "findNetworkConfigsWithKMM", ctx, node)
	ret0, _ := ret[0].([]reconcile.Request)
	return ret0
}

// findNetworkConfigsWithKMM indicates an expected call of findNetworkConfigsWithKMM.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) findNetworkConfigsWithKMM(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "findNetworkConfigsWithKMM", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).findNetworkConfigsWithKMM), ctx, node)
}

// getNetworkConfigOwnedKMMModule mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) getNetworkConfigOwnedKMMModule(ctx context.Context, nwConfig *v1alpha1.NetworkConfig) (*v1beta1.Module, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getNetworkConfigOwnedKMMModule", ctx, nwConfig)
	ret0, _ := ret[0].(*v1beta1.Module)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getNetworkConfigOwnedKMMModule indicates an expected call of getNetworkConfigOwnedKMMModule.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) getNetworkConfigOwnedKMMModule(ctx, nwConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getNetworkConfigOwnedKMMModule", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).getNetworkConfigOwnedKMMModule), ctx, nwConfig)
}

// getRequestedNetworkConfig mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) getRequestedNetworkConfig(ctx context.Context, namespacedName types.NamespacedName) (*v1alpha1.NetworkConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getRequestedNetworkConfig", ctx, namespacedName)
	ret0, _ := ret[0].(*v1alpha1.NetworkConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getRequestedNetworkConfig indicates an expected call of getRequestedNetworkConfig.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) getRequestedNetworkConfig(ctx, namespacedName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getRequestedNetworkConfig", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).getRequestedNetworkConfig), ctx, namespacedName)
}

// handleBuildConfigMap mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) handleBuildConfigMap(ctx context.Context, nwConfig *v1alpha1.NetworkConfig, nodes *v1.NodeList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleBuildConfigMap", ctx, nwConfig, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleBuildConfigMap indicates an expected call of handleBuildConfigMap.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) handleBuildConfigMap(ctx, nwConfig, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleBuildConfigMap", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).handleBuildConfigMap), ctx, nwConfig, nodes)
}

// handleDevicePlugin mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) handleDevicePlugin(ctx context.Context, nwConfig *v1alpha1.NetworkConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleDevicePlugin", ctx, nwConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleDevicePlugin indicates an expected call of handleDevicePlugin.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) handleDevicePlugin(ctx, nwConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleDevicePlugin", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).handleDevicePlugin), ctx, nwConfig)
}

// handleKMMModule mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) handleKMMModule(ctx context.Context, nwConfig *v1alpha1.NetworkConfig, nodes *v1.NodeList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleKMMModule", ctx, nwConfig, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleKMMModule indicates an expected call of handleKMMModule.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) handleKMMModule(ctx, nwConfig, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleKMMModule", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).handleKMMModule), ctx, nwConfig, nodes)
}

// handleKMMVersionLabel mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) handleKMMVersionLabel(ctx context.Context, nwConfig *v1alpha1.NetworkConfig, nodes *v1.NodeList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleKMMVersionLabel", ctx, nwConfig, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleKMMVersionLabel indicates an expected call of handleKMMVersionLabel.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) handleKMMVersionLabel(ctx, nwConfig, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleKMMVersionLabel", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).handleKMMVersionLabel), ctx, nwConfig, nodes)
}

// handleMetricsExporter mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) handleMetricsExporter(ctx context.Context, nwConfig *v1alpha1.NetworkConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleMetricsExporter", ctx, nwConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleMetricsExporter indicates an expected call of handleMetricsExporter.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) handleMetricsExporter(ctx, nwConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleMetricsExporter", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).handleMetricsExporter), ctx, nwConfig)
}

// handleModuleUpgrade mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) handleModuleUpgrade(ctx context.Context, nwConfig *v1alpha1.NetworkConfig, nodes *v1.NodeList, delete bool) (controllerruntime.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleModuleUpgrade", ctx, nwConfig, nodes, delete)
	ret0, _ := ret[0].(controllerruntime.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// handleModuleUpgrade indicates an expected call of handleModuleUpgrade.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) handleModuleUpgrade(ctx, nwConfig, nodes, delete any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleModuleUpgrade", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).handleModuleUpgrade), ctx, nwConfig, nodes, delete)
}

// handleNodeLabeller mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) handleNodeLabeller(ctx context.Context, nwConfig *v1alpha1.NetworkConfig, nodes *v1.NodeList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleNodeLabeller", ctx, nwConfig, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleNodeLabeller indicates an expected call of handleNodeLabeller.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) handleNodeLabeller(ctx, nwConfig, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleNodeLabeller", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).handleNodeLabeller), ctx, nwConfig, nodes)
}

// handleSecondaryNetwork mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) handleSecondaryNetwork(ctx context.Context, nwConfig *v1alpha1.NetworkConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleSecondaryNetwork", ctx, nwConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleSecondaryNetwork indicates an expected call of handleSecondaryNetwork.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) handleSecondaryNetwork(ctx, nwConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleSecondaryNetwork", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).handleSecondaryNetwork), ctx, nwConfig)
}

// listNetworkConfigs mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) listNetworkConfigs(ctx context.Context) (*v1alpha1.NetworkConfigList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "listNetworkConfigs", ctx)
	ret0, _ := ret[0].(*v1alpha1.NetworkConfigList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// listNetworkConfigs indicates an expected call of listNetworkConfigs.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) listNetworkConfigs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "listNetworkConfigs", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).listNetworkConfigs), ctx)
}

// setCondition mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) setCondition(ctx context.Context, condition string, nwConfig *v1alpha1.NetworkConfig, status v10.ConditionStatus, reason, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "setCondition", ctx, condition, nwConfig, status, reason, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// setCondition indicates an expected call of setCondition.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) setCondition(ctx, condition, nwConfig, status, reason, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "setCondition", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).setCondition), ctx, condition, nwConfig, status, reason, message)
}

// setFinalizer mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) setFinalizer(ctx context.Context, nwConfig *v1alpha1.NetworkConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "setFinalizer", ctx, nwConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// setFinalizer indicates an expected call of setFinalizer.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) setFinalizer(ctx, nwConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "setFinalizer", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).setFinalizer), ctx, nwConfig)
}

// updateNetworkConfigStatus mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) updateNetworkConfigStatus(ctx context.Context, nwConfig *v1alpha1.NetworkConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "updateNetworkConfigStatus", ctx, nwConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// updateNetworkConfigStatus indicates an expected call of updateNetworkConfigStatus.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) updateNetworkConfigStatus(ctx, nwConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "updateNetworkConfigStatus", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).updateNetworkConfigStatus), ctx, nwConfig)
}

// updateNodeAssignments mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) updateNodeAssignments(namespacedName string, nodes *v1.NodeList, isFinalizer bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "updateNodeAssignments", namespacedName, nodes, isFinalizer)
}

// updateNodeAssignments indicates an expected call of updateNodeAssignments.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) updateNodeAssignments(namespacedName, nodes, isFinalizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "updateNodeAssignments", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).updateNodeAssignments), namespacedName, nodes, isFinalizer)
}

// validateNetworkConfig mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) validateNetworkConfig(ctx context.Context, nwConfig *v1alpha1.NetworkConfig) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "validateNetworkConfig", ctx, nwConfig)
	ret0, _ := ret[0].([]string)
	return ret0
}

// validateNetworkConfig indicates an expected call of validateNetworkConfig.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) validateNetworkConfig(ctx, nwConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "validateNetworkConfig", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).validateNetworkConfig), ctx, nwConfig)
}

// validateNodeAssignments mocks base method.
func (m *MocknetworkConfigReconcilerHelperAPI) validateNodeAssignments(namespacedName string, nodes *v1.NodeList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "validateNodeAssignments", namespacedName, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// validateNodeAssignments indicates an expected call of validateNodeAssignments.
func (mr *MocknetworkConfigReconcilerHelperAPIMockRecorder) validateNodeAssignments(namespacedName, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "validateNodeAssignments", reflect.TypeOf((*MocknetworkConfigReconcilerHelperAPI)(nil).validateNodeAssignments), namespacedName, nodes)
}
