// Code generated by MockGen. DO NOT EDIT.
// Source: workermgr.go
//
// Generated by this command:
//
//	mockgen -source=workermgr.go -package=workermgr -destination=mock_workermgr.go WorkerMgrAPI
//
// Package workermgr is a generated GoMock package.
package workermgr

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/ROCm/network-operator/api/v1alpha1"
	logr "github.com/go-logr/logr"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	types "k8s.io/apimachinery/pkg/types"
)

// MockWorkerMgrAPI is a mock of WorkerMgrAPI interface.
type MockWorkerMgrAPI struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMgrAPIMockRecorder
}

// MockWorkerMgrAPIMockRecorder is the mock recorder for MockWorkerMgrAPI.
type MockWorkerMgrAPIMockRecorder struct {
	mock *MockWorkerMgrAPI
}

// NewMockWorkerMgrAPI creates a new mock instance.
func NewMockWorkerMgrAPI(ctrl *gomock.Controller) *MockWorkerMgrAPI {
	mock := &MockWorkerMgrAPI{ctrl: ctrl}
	mock.recorder = &MockWorkerMgrAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerMgrAPI) EXPECT() *MockWorkerMgrAPIMockRecorder {
	return m.recorder
}

// AddWorkReadyLabel mocks base method.
func (m *MockWorkerMgrAPI) AddWorkReadyLabel(ctx context.Context, logger logr.Logger, nsn types.NamespacedName, pod *v1.Pod) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddWorkReadyLabel", ctx, logger, nsn, pod)
}

// AddWorkReadyLabel indicates an expected call of AddWorkReadyLabel.
func (mr *MockWorkerMgrAPIMockRecorder) AddWorkReadyLabel(ctx, logger, nsn, pod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWorkReadyLabel", reflect.TypeOf((*MockWorkerMgrAPI)(nil).AddWorkReadyLabel), ctx, logger, nsn, pod)
}

// GetWorkReadyLabel mocks base method.
func (m *MockWorkerMgrAPI) GetWorkReadyLabel(nsn types.NamespacedName) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkReadyLabel", nsn)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetWorkReadyLabel indicates an expected call of GetWorkReadyLabel.
func (mr *MockWorkerMgrAPIMockRecorder) GetWorkReadyLabel(nsn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkReadyLabel", reflect.TypeOf((*MockWorkerMgrAPI)(nil).GetWorkReadyLabel), nsn)
}

// GetWorkerPod mocks base method.
func (m *MockWorkerMgrAPI) GetWorkerPod(ctx context.Context, networkConfig *v1alpha1.NetworkConfig, node *v1.Node) (*v1.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerPod", ctx, networkConfig, node)
	ret0, _ := ret[0].(*v1.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkerPod indicates an expected call of GetWorkerPod.
func (mr *MockWorkerMgrAPIMockRecorder) GetWorkerPod(ctx, networkConfig, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerPod", reflect.TypeOf((*MockWorkerMgrAPI)(nil).GetWorkerPod), ctx, networkConfig, node)
}

// RemoveWorkReadyLabel mocks base method.
func (m *MockWorkerMgrAPI) RemoveWorkReadyLabel(ctx context.Context, logger logr.Logger, nsn types.NamespacedName, pod *v1.Pod) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveWorkReadyLabel", ctx, logger, nsn, pod)
}

// RemoveWorkReadyLabel indicates an expected call of RemoveWorkReadyLabel.
func (mr *MockWorkerMgrAPIMockRecorder) RemoveWorkReadyLabel(ctx, logger, nsn, pod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWorkReadyLabel", reflect.TypeOf((*MockWorkerMgrAPI)(nil).RemoveWorkReadyLabel), ctx, logger, nsn, pod)
}

// Undo mocks base method.
func (m *MockWorkerMgrAPI) Undo(ctx context.Context, networkConfig *v1alpha1.NetworkConfig, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Undo", ctx, networkConfig, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// Undo indicates an expected call of Undo.
func (mr *MockWorkerMgrAPIMockRecorder) Undo(ctx, networkConfig, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Undo", reflect.TypeOf((*MockWorkerMgrAPI)(nil).Undo), ctx, networkConfig, node)
}

// Work mocks base method.
func (m *MockWorkerMgrAPI) Work(ctx context.Context, networkConfig *v1alpha1.NetworkConfig, node *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Work", ctx, networkConfig, node)
	ret0, _ := ret[0].(error)
	return ret0
}

// Work indicates an expected call of Work.
func (mr *MockWorkerMgrAPIMockRecorder) Work(ctx, networkConfig, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Work", reflect.TypeOf((*MockWorkerMgrAPI)(nil).Work), ctx, networkConfig, node)
}
