// Code generated by MockGen. DO NOT EDIT.
// Source: validator.go
//
// Generated by this command:
//
//	mockgen -source=validator.go -package=validator -destination=mock_validator.go ValidatorAPI
//
// Package validator is a generated GoMock package.
package validator

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/ROCm/network-operator/api/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockValidatorAPI is a mock of ValidatorAPI interface.
type MockValidatorAPI struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorAPIMockRecorder
}

// MockValidatorAPIMockRecorder is the mock recorder for MockValidatorAPI.
type MockValidatorAPIMockRecorder struct {
	mock *MockValidatorAPI
}

// NewMockValidatorAPI creates a new mock instance.
func NewMockValidatorAPI(ctrl *gomock.Controller) *MockValidatorAPI {
	mock := &MockValidatorAPI{ctrl: ctrl}
	mock.recorder = &MockValidatorAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidatorAPI) EXPECT() *MockValidatorAPIMockRecorder {
	return m.recorder
}

// ValidateNetworkConfigAll mocks base method.
func (m *MockValidatorAPI) ValidateNetworkConfigAll(ctx context.Context, client client.Client, nwConfig *v1alpha1.NetworkConfig) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateNetworkConfigAll", ctx, client, nwConfig)
	ret0, _ := ret[0].([]string)
	return ret0
}

// ValidateNetworkConfigAll indicates an expected call of ValidateNetworkConfigAll.
func (mr *MockValidatorAPIMockRecorder) ValidateNetworkConfigAll(ctx, client, nwConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateNetworkConfigAll", reflect.TypeOf((*MockValidatorAPI)(nil).ValidateNetworkConfigAll), ctx, client, nwConfig)
}

// ValidateNetworkConfigSpec mocks base method.
func (m *MockValidatorAPI) ValidateNetworkConfigSpec(ctx context.Context, client client.Client, nwConfig *v1alpha1.NetworkConfig, specs []string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateNetworkConfigSpec", ctx, client, nwConfig, specs)
	ret0, _ := ret[0].([]string)
	return ret0
}

// ValidateNetworkConfigSpec indicates an expected call of ValidateNetworkConfigSpec.
func (mr *MockValidatorAPIMockRecorder) ValidateNetworkConfigSpec(ctx, client, nwConfig, specs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateNetworkConfigSpec", reflect.TypeOf((*MockValidatorAPI)(nil).ValidateNetworkConfigSpec), ctx, client, nwConfig, specs)
}
